name: mir-kiosk-dalrao-app
version: '0.15'
summary: Application for Mir-Kiosk, designed to display information and control the hydraulic station.
description: This application allows you to work with the DalRao hydraulic station: configuration of the number of tables and trolleys in the pillows, information on engine operation (tachometer, hydraulic fluid, oil, etc.). The application allows you to switch between dark and light themes for comfortable work at any time of the day.
base: core20
confinement: strict
grade: devel

apps:    
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/run.sh
      
  mir-kiosk-dalrao-app:
    command-chain:
      - bin/wayland-launch
    command: bin/run.sh

environment:
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:
  myprog:
    plugin: dump
    source: ./bin/${SNAPCRAFT_ARCH_TRIPLET}
    organize:
      main: bin/main
      main1: bin/main1
      
  run-script:
    plugin: dump
    source: ./bin/general
    organize:
      run.sh: bin/run.sh
      correct_address.sh: bin/correct_address.sh
            
  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa
      #qt5     
      - qt5-default
      - qtdeclarative5-dev
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qtwayland5
      - qml-module-qtquick-extras
      - qml-module-qt-labs-settings
      
      #- libfreetype6
      #- libpng16-16
      #- libharfbuzz0b
      #- libpcre2-16-0

  correct-locale:
    plugin: nil
    override-prime: $SNAPCRAFT_PRIME/bin/correct_address.sh
    after:
      - mesa
      - run-script

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
    stage-packages:
      - inotify-tools
