name: dalrao-app
version: '0.26'
summary: Display information and control the hydraulic station
description: Management of tables and carts, information on the state of the engine for the hydraulic station DalRao
base: core20
confinement: strict
grade: stable

apps:
 udisksd:
   command: libexec/udisks2/udisksd
   daemon: simple
   slots: [ service ]
   plugs:
     - hardware-observe
     - mount-observe
 automount:
   command: bin/automount
   daemon: simple
   after: [ udisksd ]
   plugs:
     - client
 udiskctl:
   command: bin/udiskctl.sh
   plugs:
     - client
     
 daemon:
   daemon: simple
   restart-condition: never
   command-chain:
     - bin/run-daemon
     - bin/wayland-launch
   command: bin/run.sh
   plugs:
     -  opengl
     -  wayland
     -  network     
     -  raw-usb
     -  removable-media  
 dalrao-app:
   command-chain:
     - bin/wayland-launch
   command: bin/run.sh
   plugs:
     -  opengl
     -  wayland
     -  network
     -  raw-usb
     -  removable-media
     
slots:
  service:
    interface: udisks2
plugs:
  client:
    interface: udisks2
    
layout:
  /var/lib/udisks2:
    bind: $SNAP_DATA/var/lib/udisks2
  /etc/udisks2/udisks2.conf:
    bind-file: $SNAP/etc/udisks2/udisks2.conf
  /etc/libblockdev/conf.d:
    bind: $SNAP/etc/libblockdev/conf.d

environment:
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:      
  udisks:
    source: https://github.com/storaged-project/udisks.git
    source-tag: udisks-2.9.1
    plugin: autotools
    override-pull: |
      snapcraftctl pull
      git apply -v ../../../udisksd.patch
    configflags:
        - --enable-fhs-media
    install-via: destdir
    build-packages:
        - pkg-config
        - xsltproc
        - gtk-doc-tools
        - intltool
        - libglib2.0-dev
        - udev
        - libgudev-1.0-dev
        - libpolkit-gobject-1-dev
        - libpolkit-agent-1-dev
        - libacl1-dev
        - libgirepository1.0-dev
        - gobject-introspection
        - libatasmart-dev
        - libsystemd-dev
        - libmount-dev
    stage-packages:
        - libacl1
        - libatasmart4
        - libglib2.0-0
        - libgudev-1.0-0
        - libpam-systemd
        - libpolkit-agent-1-0
        - libpolkit-gobject-1-0
        - parted
        - libmount1
    filesets:
      licenses:
          - usr/share/doc/*/*copyright*
      binaries:
          - bin/udisksctl
          - libexec/udisks2/udisksd
    prime:
        - $binaries
        - $licenses
        - lib
        - -lib/pkgconfig
        - -lib/systemd
        - -lib/cgmanager
        - libexec
        - sbin
        - usr/lib/*/*.so*
        
  myprog:
    plugin: dump
    source: ./bin/${SNAPCRAFT_ARCH_TRIPLET}
    organize:
      main: bin/main
      
  run-script:
    plugin: dump
    source: ./bin/general
    organize:
      run.sh: bin/run.sh
      correct_address.sh: bin/correct_address.sh
      automount: bin/automount
      udiskctl.sh: bin/udiskctl.sh
            
  mesa:
    plugin: nil
    stage-packages:
      #- libgl1-mesa-dri
      - libgles2-mesa-dev
      #- libwayland-egl1-mesa
      #- libglu1-mesa
      #- usbmount
      #qt5     
      - qt5-default
      - qtdeclarative5-dev
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qtwayland5
      - qml-module-qtquick-extras
      - qml-module-qt-labs-settings

  correct-locale:
    plugin: nil
    override-prime: $SNAPCRAFT_PRIME/bin/correct_address.sh
    after:
      - mesa
      - run-script
      
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network raw-usb removable-media
    stage-packages:
      - inotify-tools
