name: dalrao-app
version: '0.1'
summary: test snap version for mir kiosk
description: example kiosk, using Wayland
base: core20
confinement: strict
grade: devel

apps:
  dalrao-app:
    command: bin/wayland-launch $SNAP/bin/run.sh
    plugs:
    -  opengl
    -  wayland
    -  network
    
  daemon:
    command: bin/run-daemon bin/wayland-launch $SNAP/bin/run.sh
    daemon: simple
    restart-condition: always
    plugs:
    -  opengl
    -  wayland
    -  network

environment:
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:
  myprog:
    plugin: dump
    source: ./bin/${SNAPCRAFT_ARCH_TRIPLET}
    organize:
      main: bin/main
      main1: bin/main1
      
  run-script:
    plugin: dump
    source: ./bin/general
    organize:
      run.sh: bin/run.sh
      correct_address.sh: bin/correct_address.sh
            
  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa
      #qt5     
      - qt5-default
      - qtdeclarative5-dev
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qtwayland5
      - qml-module-qtquick-extras
      - qml-module-qt-labs-settings
      #other
      - inotify-tools
      - procps
      
      #- libfreetype6
      #- libpng16-16
      #- libharfbuzz0b
      #- libpcre2-16-0

  correct-locale:
    plugin: nil
    override-prime: $SNAPCRAFT_PRIME/bin/correct_address.sh
    after:
      - mesa
      - run-script

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
